import Header from "../components/Header";
import Head from "next/head";
export default function About() {
  return (
    <>
      <Head>
        <title>unitytrade+ | about</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" href="/info.png" />
      </Head>

      <Header
        quote="The privilege of a lifetime is to become who you truly are."
        author="Carl Jung"
      />

      <div className="w3-row w3-padding w3-border">

        <div className="w3-col w3-display-container w3-padding w3-hide-large w3-hide-medium">
          <img className="w3-image w3-sepia" src="/about.gif" alt="ABOUT" style={{ width: '100%' }} />
          <div className="w3-display-middle">
            <span className="w3-jumbo w3-hide-small w3-text-dark-grey"><b>ABOUT</b> </span>
            <span className="w3-xlarge w3-hide-large w3-hide-medium w3-text-dark-grey"><b>ABOUT</b> </span>
          </div>
        </div>

        <div className="w3-col w3-display-container  w3-hide-small w3-center w3-white">
          <img className="w3-image w3-sepia" src="/about.gif" alt="ABOUT" style={{ width: '50%' }} />
          <div className="w3-display-middle">
            <span className="w3-jumbo w3-hide-small w3-text-dark-grey"><b>ABOUT</b> </span>
            <span className="w3-xlarge w3-hide-large w3-hide-medium w3-text-dark-grey"><b>ABOUT</b> </span>
          </div>
        </div>

        <div className="w3-white w3-margin">
          <div className="w3-container w3-black">
            <h4>WHO ARE WE</h4>
          </div>
          <p className="w3-padding">
            This project is mainly focused to implement a web-based platform which can be used as
            a help tool for traders. In this application, three factors will be considered to generate
            predictions. They are candlestick charts analysis, forex trading news analysis, suggestions
            which are available in social media trading community groups. Prediction can be
            generated by the centralized logical module of this platform by processing the data
            retrieved from the above three methods. Then after those predictions will be sent to
            traders who is using our platform to trade. These related things will be covered on this
            chapter one by one according to requirement of sub topics.<br />
            <br />
            In a day-to-day life, many transactions are dealt by traders with several platforms by
            investing money and a high profit are being received by these platforms as well as these
            trading platforms may have got high risk. There are traders are being affected by the
            technical analysis and fundamental analysis of trading domain. Those factors will be
            considered when the order is being sold and bought in these trading platforms. There for,
            traders time is spent by analyzing those kinds of technical and fundamental factors. But in
            this platform which is going to be made by us, forex news will be analyzed from
            investing.com and candlestick chart pattern recognize will be generated and Suggestions
            which will have been given by professional traders will be given to the traders at same
            time. This is novelty of our project that three predictions will be generated on our platform
            at same time. Therefor traders time will be saved and risk are being reduced by our
            platform.
            <br /><br />
            Initially, this project idea had been introduced by one of our group members. Then after,
            basic information about these kind of trading systems had been searched to be known by
            us to make our novelty platform. These things had been discussed and decided with our
            supervisor panel to get upgraded platform with more features. Many things could be
            understood by us from supervisors advise then some novelty ideas had been raised within
            us that they are this chart analysis could be automated and forex news details could be
            analyzed and prediction could be retrieved from advisors, traders who is using our platform
            could be helped to save their time and avoid some human errors. Some basic points had
            been analyzed by us when we study about trading. Gathered information had been
            implemented as solution which should be manipulated on our system. We had been
            motivated by these things to go-ahead this project.<br /><br />
            There are So many factors affecting the technical analysis and fundamental analysis of the
            trading domain. Ex; currency rates, indicators, financial decisions, etc. In this project all
            these factors will not be considered to give the prediction. Only candlestick chart patterns,
            forex news site details and suggestions from other traders in telegram groups for the forex
            market under the currency rate of EUR/USD will be considered in the design and future
            implementation of this project. Open source, a pre-build library called ta-lib will be used
            for candlestick chart pattern recognition. And investing.com website economic calendar
            will be used via investpy python package or user of this application to get forex news data
            for EUR/USD currency rate. And suggestions from other traders who post their predictions
            in telegram trade help groups will be received to this application. At the last, all data
            retrieved from candlestick chart pattern recognition, investing.com website economic
            calendar and suggestions of other traders will be processed to generate predictions. Finally,
            those predictions will be sent to the user via the telegram app.
          </p>
        </div>

        <div className="w3-white w3-margin">
          <div className="w3-container w3-black">
            <h4>OUR MISSION</h4>
          </div>
          <p className="w3-padding">
            In this application, three factors will be considered to generate predictions. There are
            candlestick chart analysis, forex trading news analysis, suggestions of traders in social
            media trading community groups. Predictions can be generated by the centralized logical
            module of this application by processing the data retrieved from the above three methods.
            After generating predictions, those predictions will be received by the user
            <br /><br />
            After a user request from his/her advisor in this system by giving details of order which
            user is going to place, suggestions will be given by the advisor in this system before the
            user places the order. Those predictions can be got by the user to make success his/her
            order
            <br /><br />
            After some advisor is selected by the user, user have to pay for that advisor to get
            predictions. Finally, some money can be earned by the advisors of this system.
            <br /><br />
          </p>
        </div>

        <div className="w3-white w3-margin">
          <div className="w3-container w3-black">
            <h4>OUR VISION</h4>
          </div>
          <p className="w3-padding">
            The system gives forex trading signals for five-time frames. It occurs via using forex
            candlestick data, forex news, and Telegram's forex trading signals. First, the system
            fetches forex daily news on investing.com, then analyzes this news and creates forex
            signals. Second, the system fetches candlestick data from Yahoo Finance and analyzes this
            candlestick data to create a signal. Finally, the system fetches forex trading signals from
            Telegram groups. In addition, the system generates telegram signals from five-time
            frames.<br /><br />
            This project is mainly focused to implement a web-based platform that can be used as a
            helpful tool for traders. Data fetched from three ways will be analyzed and generated
            predictions based on that proceed data and finally those predictions will be sent to the user.
            A good profit is earned by forex traders by investing money in the trading platforms. Forex
            market analysis can be divided into two main categories as technical and fundamental
            analysis. And the time is spent by traders to analyze those technical and fundamental
            factors. Because predictions will be generated and provided by our platform at same time
            considering technical and fundamental factors, traders time will be saved and risk are being
            6
            reduced by our platform. But there are assumptions that is considered when this application
            is being developed. Forex traders will be users of this system. Several things such as log
            in, register, etc... can be done by the user. And details such as login, register, request and
            give predictions details are the inputs of this system. Receive predictions generated by this
            system to the user, receive predictions posted by the advisors of this system to the user,
            earn money by advisors for giving services to their customers are overall outputs of this
            system. To achieve overall outputs, fetched data will be analyzed and predictions will be
            generated by the system. And facilities will be provided by the system to users and advisors
            to get and post predictions<br /><br />
          </p>
        </div>

      </div>
    </>
  )

}